### ISSUE TITLE
Add dedupe to node-resolve config

### ISSUE THREAD

**Issue by antony** [rixo/svelte-template-hot#3]
Hi @rixo !

I'm trying out the template on some smaller projects, so I'll raise any issues I find.

First one is that you get a lot of errors if you're trying to link modules, and this is because the template is missing `dedupe` config.

**Comment by antony** [comment]
Just noticed the comment below about auto-dedupe. I'm not sure it works though, since adding dedupe seemed to solve an issue I was having. I'll investigate a bit more.

**Comment by antony** [comment]
Without dedupe: [ 'svelte' ] in my config, I get the following error when using linked modules:

```
[!] Error: 'validate_slots' is not exported by ../../beyonk-shared/node_modules/svelte/internal/index.mjs, imported by ../../beyonk-shared/packages/booking-form/lib/sliding-form/SlidingForm.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
```

**Comment by rixo** [comment]
Hey! Nice to hear! (Not the bug, but that you're experimenting with simplest setups...)

Indeed, the implemented dedup mainly targeted the situation where both the consumer (the template) and the Rollup hot plugin (symlink, under development) both includes their own version of Svelte.

Apparently your case is multiple projects publishing components, symlinked and... Why do they all embark their own version of Svelte, by the way? Testing? And why do they differ across the projects?

Anyway, I thought my dedup would address this case too, but I haven't tested it thoroughly. I'm giving it another look, and I'll re add the dedup option in Rollup if needed.

**Comment by rixo** [comment]
OK I've restored the dedupe option.

I'm a bit concerned that with that you can end up with a different Svelte used to compile your components, as the one that gets imported/bundled with them (the runtime)... But my algorithm is clearly not infaillible either, so probably better to stay aligned for now.

Do you happen to use the [`rootDir`](https://github.com/rollup/plugins/tree/master/packages/node-resolve#rootdir) option of the `node-resolve` plugin, somewhere?

Also I see that there has been some recent development in official Svelte plugin that I need to catch up with. I'll try to see if something better can be done then.

Thanks for feedback :)
