### ISSUE TITLE
svelte-flatpickr, localization, import object is undefined with nollup

### ISSUE THREAD

**Issue by frederikhors** [rixo/svelte-template-hot#8]
I'm trying to use [`svelte-flatpickr`](https://github.com/jacobmischka/svelte-flatpickr) which works very good with `npm run dev:rollup`.

Here a reproduction: https://github.com/frederikhors/svelte-template-hot/tree/svelte-flatpickr-localization.

This is the code: https://github.com/frederikhors/svelte-template-hot/blob/svelte-flatpickr-localization/src/FlatPickr.svelte:

I'm following the docs here: https://flatpickr.js.org/localization/.

```svelte
<script>
  import Flatpickr from "svelte-flatpickr";
  import { French } from "flatpickr/dist/l10n/fr.js";
  console.log("French", French); // why this is undefined?

  export let date = null;
  
  const options = {
    enableTime: true,
    locale: French,
    defaultDate: date,
    allowInput: true,
  };
</script>

<Flatpickr {options} bind:value={date} />
```

But this line: `import { French } from "flatpickr/dist/l10n/fr.js"` doesn't work: `French` is `undefined`.

Why?

**Comment by rixo** [comment]
Flatpickr's localization files are transpiled to [some kind](https://github.com/flatpickr/flatpickr/blob/49a73d6f4c447fe69aace447696b91be7b1e37d4/src/tsconfig.json#L5) of legacy module -- this apparently supports CommonJS, AMD, a window global... But this is not an ES6 module that Rollup / Nollup would natively expect.

To be honest, I'm a little surprised that Rollup can eat that. This is apparently thanks to the `commonjs` plugin. Now, if the `commonjs` plugin works for Rollup, why doesn't it work with Nollup? Can't tell... There seems to be some interop issue between Nollup and this plugin.

I think your best bet is to reduce the repro to the minimum (just flatpickr, an index.html, and a single js file that imports a l10n file to demonstrate the problem, no Svelte), and bring the issue to Nollup.

I'm keeping the issue open for now, as a reminder to move the discussion myself if need be, when I get some time... But this is most probably not something I can fix in the plugins I maintain.

**Comment by frederikhors** [comment]
**It works if I use this:**

```js
import French from "flatpickr/dist/l10n/fr.js";

...

locale: French.fr
```

**Comment by frederikhors** [comment]
I opened this: https://github.com/PepsRyuu/nollup/issues/154.

**Comment by PepsRyuu** [comment]
Discovered the problem. Looks like ```syntheticNamedExports``` was updated to allow a string rather than just a boolean. https://rollupjs.org/guide/en/#synthetic-named-exports  The CommonJS plugins exports to ```__moduleExports```.

This can be easily supported. I have it prototyped already and have it working for the reproduction. I'll have it released at some point over the next few days once I test it further.

**Comment by rixo** [comment]
Wow curious to see how you will fix it because the whole situation remains a bit cryptic for me. Thanks a lot, like always :)

**Comment by rixo** [comment]
I see this has been fixed in Nollup.

@frederikhors can you confirm if this issue is gone with last version of Nollup?

**Comment by frederikhors** [comment]
Yep.
